# coding: utf-8

"""
    Platform Operations Rest API

    The Platform Operations REST API can be leveraged to customize the Platform Operator experience of managing infrastructure and applications for the Apprenda Platform. This allows some of the functionality of the Platform's System Operations Center (SOC) to be accomplished through a variety of means such as custom-built UX or command-line interfaces.   For more information about the abilities of Platform Operators, see our documentation on the [SOC](/current/SOC).   ##Authentication   Before making a request, you must be authenticated. Learn how to [get authenticated](/restapi/platformops/v1/authentication).   ##Making a Request   ###Prerequisites   * Installed Platform of version 6.5.1 or later (Note that most endpoints are only available in verison 6.7.0 and later)    * Authentication token   * If SOC authorization is enabled on your Platform, you must be assigned as an active Platform Operator   ###Request URL   All requests must use **https**.   The URL for every request you make is the Cloud URI of your Platform followed by \"/soc\" and the path structure of the endpoint. For example, if your Cloud URI is apps.apprenda.harp and you want to get the Add-ons for your Platform, the request URI will be **apps.apprenda.harp/soc/api/v1/addons**.   For more information, see our documentation on [using API resources](/restapi/platformops/v1/using-resources) and [finding your Cloud URI](/current/clouduri).   ###Request Headers   Your authenication token must be passed in the header of all requests using the key **ApprendaSessionToken** (not case sensitive).  

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.add_on import AddOn
from .models.add_on_creation_request import AddOnCreationRequest
from .models.application import Application
from .models.apprenda_file_system_file_system_uri import ApprendaFileSystemFileSystemUri
from .models.apprenda_rest_api_common_resources_paged_resource_base_application import ApprendaRestAPICommonResourcesPagedResourceBaseApplication
from .models.apprenda_rest_api_common_resources_paged_resource_base_version import ApprendaRestAPICommonResourcesPagedResourceBaseVersion
from .models.apprenda_rest_api_common_resources_resource_base import ApprendaRestAPICommonResourcesResourceBase
from .models.apprenda_soc_web_rest_api_resources_bootstrap_policy import ApprendaSOCWebRestAPIResourcesBootstrapPolicy
from .models.apprenda_utility_rest_api_common_resources_resource_base import ApprendaUtilityRestAPICommonResourcesResourceBase
from .models.cloud import Cloud
from .models.component import Component
from .models.custom_property import CustomProperty
from .models.custom_property_applicability_option import CustomPropertyApplicabilityOption
from .models.custom_property_applicability_option_collection import CustomPropertyApplicabilityOptionCollection
from .models.custom_property_application_component_options import CustomPropertyApplicationComponentOptions
from .models.custom_property_application_options import CustomPropertyApplicationOptions
from .models.custom_property_developer_options import CustomPropertyDeveloperOptions
from .models.custom_property_update import CustomPropertyUpdate
from .models.custom_property_value_options import CustomPropertyValueOptions
from .models.deployment_policy import DeploymentPolicy
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001
from .models.inline_response_400 import InlineResponse400
from .models.node_state import NodeState
from .models.paged_resource_base_custom_property import PagedResourceBaseCustomProperty
from .models.paged_resource_base_registry_setting import PagedResourceBaseRegistrySetting
from .models.registry_setting import RegistrySetting
from .models.resource_allocation_report import ResourceAllocationReport
from .models.unpaged_resource_base_add_on import UnpagedResourceBaseAddOn
from .models.unpaged_resource_base_bootstrap_policy import UnpagedResourceBaseBootstrapPolicy
from .models.unpaged_resource_base_cloud import UnpagedResourceBaseCloud
from .models.unpaged_resource_base_component import UnpagedResourceBaseComponent
from .models.unpaged_resource_base_deployment_policy import UnpagedResourceBaseDeploymentPolicy
from .models.unpaged_resource_base_workload import UnpagedResourceBaseWorkload
from .models.version import Version
from .models.visibility_options import VisibilityOptions
from .models.workload import Workload
from .models.workload_deployment_request import WorkloadDeploymentRequest

# import apis into sdk package
from .apis.add_ons_api import AddOnsApi
from .apis.applications_api import ApplicationsApi
from .apis.bootstrap_policies_api import BootstrapPoliciesApi
from .apis.clouds_api import CloudsApi
from .apis.components_api import ComponentsApi
from .apis.custom_properties_api import CustomPropertiesApi
from .apis.deployment_policies_api import DeploymentPoliciesApi
from .apis.hosts_api import HostsApi
from .apis.registry_api import RegistryApi
from .apis.versions_api import VersionsApi
from .apis.workloads_api import WorkloadsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
